# Form implementation generated from reading ui file 'giaodienchinh.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Khuon_Mat_Cam_Xuc(object):
    def setupUi(self, Khuon_Mat_Cam_Xuc):
        Khuon_Mat_Cam_Xuc.setObjectName("Khuon_Mat_Cam_Xuc")
        Khuon_Mat_Cam_Xuc.resize(677, 484)
        self.centralwidget = QtWidgets.QWidget(parent=Khuon_Mat_Cam_Xuc)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 561, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bt_UL = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_UL.setGeometry(QtCore.QRect(130, 100, 93, 28))
        self.bt_UL.setObjectName("bt_UL")
        self.bt_WC = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_WC.setGeometry(QtCore.QRect(480, 100, 131, 28))
        self.bt_WC.setObjectName("bt_WC")
        self.anh_goc = QtWidgets.QListView(parent=self.centralwidget)
        self.anh_goc.setGeometry(QtCore.QRect(30, 150, 361, 271))
        self.anh_goc.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.anh_goc.setObjectName("anh_goc")
        self.anh_mat = QtWidgets.QListView(parent=self.centralwidget)
        self.anh_mat.setGeometry(QtCore.QRect(470, 180, 151, 111))
        self.anh_mat.setObjectName("anh_mat")
        self.cam_xuc = QtWidgets.QListView(parent=self.centralwidget)
        self.cam_xuc.setGeometry(QtCore.QRect(440, 350, 201, 31))
        self.cam_xuc.setObjectName("cam_xuc")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 160, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 330, 151, 16))
        self.label_3.setObjectName("label_3")
        Khuon_Mat_Cam_Xuc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Khuon_Mat_Cam_Xuc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 26))
        self.menubar.setObjectName("menubar")
        Khuon_Mat_Cam_Xuc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Khuon_Mat_Cam_Xuc)
        self.statusbar.setObjectName("statusbar")
        Khuon_Mat_Cam_Xuc.setStatusBar(self.statusbar)

        self.retranslateUi(Khuon_Mat_Cam_Xuc)
        QtCore.QMetaObject.connectSlotsByName(Khuon_Mat_Cam_Xuc)

    def retranslateUi(self, Khuon_Mat_Cam_Xuc):
        _translate = QtCore.QCoreApplication.translate
        Khuon_Mat_Cam_Xuc.setWindowTitle(_translate("Khuon_Mat_Cam_Xuc", "Nhận diện khuôn mặt và cảm xúc"))
        self.label.setText(_translate("Khuon_Mat_Cam_Xuc", "Nhận diện cảm xúc từ khuôn mặt"))
        self.bt_UL.setText(_translate("Khuon_Mat_Cam_Xuc", "Tải ảnh lên"))
        self.bt_WC.setText(_translate("Khuon_Mat_Cam_Xuc", "Sử dụng webcam"))
        self.label_2.setText(_translate("Khuon_Mat_Cam_Xuc", "Khuôn mặt nhận diện được"))
        self.label_3.setText(_translate("Khuon_Mat_Cam_Xuc", "Cảm xúc nhận diện được"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Khuon_Mat_Cam_Xuc = QtWidgets.QMainWindow()
    ui = Ui_Khuon_Mat_Cam_Xuc()
    ui.setupUi(Khuon_Mat_Cam_Xuc)
    Khuon_Mat_Cam_Xuc.show()
    sys.exit(app.exec())
